name: Authenticate with Google Cloud + Artifact Registry
description: Checks if pyproject.toml version changed and, if so, builds and publishes new package
inputs:
  credentials:
    description: JSON credentials file for auth
    type: string
    required: true

  enable_private_docker:
    description: Should the environment be updated to enable private GAR-based Docker?
    type: boolean
    required: false
    default: false

  enable_private_pypi:
    description: Should the environment be updated to enable private GAR-based PyPI?
    type: boolean
    required: false
    default: false
outputs:
  # these are all provided by auth
  project_id:
    description: Provided or extracted value for the Google Cloud project ID.
    value: ${{ steps.auth.outputs.project_id }}
  credentials_file_path:
    description: Path on the local filesystem where the generated credentials file resides. Provided by Google auth action.
    value: ${{ steps.auth.outputs.credentials_file_path }}
  auth_token:
    description: The Google Cloud federated token (for Workload Identity Federation) or self-signed JWT (for a Service Account Key JSON).
    value: ${{ steps.auth.outputs.auth_token }}
  access_token:
    description: The Google Cloud access token for calling other Google Cloud APIs.
    value: ${{ steps.auth.outputs.access_token }}

runs:
  using: "composite"
  steps:
    - name: Auth to Google Cloud
      id: auth
      # https://github.com/google-github-actions/auth#authenticating-via-service-account-key-json-1
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ inputs.credentials }}'
        token_format: 'access_token'

    - name: Auth to Google Artifact Registry
      if: ${{ inputs.enable_private_docker }}
      shell: bash
      # https://github.com/google-github-actions/auth#authenticating-to-container-registry-and-artifact-registry
      # requires role: roles/iam.serviceAccountTokenCreator
      run: |-
        echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://us-docker.pkg.dev

    - name: Setup IAM PyPI
      if: ${{ inputs.enable_private_pypi }}
      shell: bash
      run: |
          # install keyring so pip can talk to GAR PyPI
          pip install keyrings.google-artifactregistry-auth
